tupelos:
  local:
    build: .

testers:
  js-sdk-latest:
    image: quorumcontrol/tupelo-js-sdk:latest
    command: ["npx", "mocha", "--exit"]
  js-sdk-master:
    image: quorumcontrol/tupelo-js-sdk:master
    command: ["npx", "mocha", "--exit"]
