version: 0.2

env:
  parameter-store:
    SSH_KEY: "/codebuild/qc-build-bot-rsa"

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY\n" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval `ssh-agent`
      - ssh-add ~/.ssh/id_rsa
      - bin/install-dep.sh
      - /go/bin/dep ensure
  build:
    commands:
      - for i in 1..12; do echo "Test run $i" && env GOCACHE=off go test ./... -tags=integration -timeout 2m || exit 1; done
