version: "3"
services:
  bootstrap:
    build: .
    command: ["bootstrap-node", "--config", "/configs/bootstrap/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
    volumes:
      - ./configs/localdocker:/configs      
    networks:
      default:
        ipv4_address: 172.16.238.10
    ports:
      - "34001:34001"
      
  node0:
    depends_on: 
      - bootstrap
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["node", "--config", "/configs/node0/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-error}"]

  node1:
    depends_on: 
      - bootstrap
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["node", "--config", "/configs/node1/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-error}"]
  
  node2:
    depends_on: 
      - bootstrap
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["node", "--config", "/configs/node2/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-error}"]

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
