version: "3"
services:
  bootstrap:
    build: .
    command: ["bootstrap-node", "--config", "/configs/bootstrap/config.toml"]
    volumes:
      - ./configs/localdocker:/configs      
    networks:
      default:
        ipv4_address: 172.16.238.10
    ports:
      - "34001:34001"
      
  node0:
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["test-node", "--config", "/configs/node0/config.toml"]

  node1:
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["test-node", "--config", "/configs/node1/config.toml"]
  
  node2:
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["test-node", "--config", "/configs/node2/config.toml"]

  rpc-server:
    build: .
    volumes:
      - ./configs/localdocker:/configs
    command: ["rpc-server","-r", "-l", "0", "--config", "/configs/rpcserver/config.toml"]
    ports:
      - "50051:50051"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
