version: "3"
services:
  benchmark:
    build: .
    volumes:
      - ./cmd/testnode-local-keys:/bootstrap-keys
    command: ["benchmark", "-k", "/bootstrap-keys", "-d", "300", "-c", "2", "-i", "60", "-s", "tps", "-t", "65"]
    environment:
      TUPELO_BOOTSTRAP_NODES: "/ip4/172.16.238.10/tcp/34001/ipfs/16Uiu2HAm3TGSEKEjagcCojSJeaT5rypaeJMKejijvYSnAjviWwV5"
