version: "3"
services:
  node0:
    build: .
    image: qc3:latest
    volumes:
      - .storage:/var/lib/qc3/.storage:delegated
    command: ["/usr/bin/qc3", "test-node", "-g", "-i", "0"]
  node1:
    build: .
    volumes:
      - .storage:/var/lib/qc3/.storage:delegated
    command: ["/usr/bin/qc3", "test-node", "-g", "-i", "1"]
  node2:
    build: .
    volumes:
      - .storage:/var/lib/qc3/.storage:delegated
    command: ["/usr/bin/qc3", "test-node", "-g", "-i", "2"]
