version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.16
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    #   networks:
    #     default:
    #       ipv4_address: 172.16.238.10  
    ports:
      - 16686:16686
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 16686
      - 14268
      - 14250
      - 9411
    

# you can use these settings in the other docker-compose using the environment
# you MUST set JAEGER_AGENT_HOST=jaeger in order to use this.
    #   JAEGER_SERVICE_NAME	The service name
    #   JAEGER_AGENT_HOST	The hostname for communicating with agent via UDP
    #   JAEGER_AGENT_PORT	The port for communicating with agent via UDP
    #   JAEGER_ENDPOINT	The HTTP endpoint for sending spans directly to a collector, i.e. http://jaeger-collector:14268/api/traces
    #   JAEGER_USER	Username to send as part of "Basic" authentication to the collector endpoint
    #   JAEGER_PASSWORD	Password to send as part of "Basic" authentication to the collector endpoint
    #   JAEGER_REPORTER_LOG_SPANS	Whether the reporter should also log the spans
    #   JAEGER_REPORTER_MAX_QUEUE_SIZE	The reporter's maximum queue size
    #   JAEGER_REPORTER_FLUSH_INTERVAL	The reporter's flush interval, with units, e.g. "500ms" or "2s" (valid units)
    #   JAEGER_SAMPLER_TYPE	The sampler type
    #   JAEGER_SAMPLER_PARAM	The sampler parameter (number)
    #   JAEGER_SAMPLER_MANAGER_HOST_PORT	The HTTP endpoint when using the remote sampler, i.e. http://jaeger-agent:5778/sampling
    #   JAEGER_SAMPLER_MAX_OPERATIONS	The maximum number of operations that the sampler will keep track of
    #   JAEGER_SAMPLER_REFRESH_INTERVAL	How often the remotely controlled sampler will poll jaeger-agent for the appropriate sampling strategy, with units, e.g. "1m" or "30s" (valid units)
    #   JAEGER_TAGS	A comma separated list of name = value tracer level tags, which get added to all reported spans. The value can also refer to an environment variable using the format ${envVarName:default}, where the :default is optional, and identifies a value to be used if the environment variable cannot be found
    #   JAEGER_DISABLED	Whether the tracer is disabled or not. If true, the default opentracing.NoopTracer is used.
    #   JAEGER_RPC_METRICS	Whether to store RPC metrics
    #   By default, the client sends traces via UDP to the agent at localhost:6831. Use JAEGER_AGENT_HOST and JAEGER_AGENT_PORT to send UDP traces to a different host:port. If JAEGER_ENDPOINT is set, the client sends traces to the endpoint via HTTP, making the JAEGER_AGENT_HOST and JAEGER_AGENT_PORT unused. If JAEGER_ENDPOINT is secured, HTTP basic authentication can be performed by setting the JAEGER_USER and JAEGER_PASSWORD environment variables.      