version: "3"
services:
  node0:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "0"]
    volumes:
      - node0:/var/lib/qc3
      - ./keys.json:/keys.json
  node1:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "1"]
    volumes:
      - node1:/var/lib/qc3
      - ./keys.json:/keys.json
  node2:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "2"]
    volumes:
      - node2:/var/lib/qc3
      - ./keys.json:/keys.json
  node3:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "3"]
    volumes:
      - node3:/var/lib/qc3
      - ./keys.json:/keys.json
  node4:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "4"]
    volumes:
      - node4:/var/lib/qc3
      - ./keys.json:/keys.json
  node5:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "5"]
    volumes:
      - node5:/var/lib/qc3
      - ./keys.json:/keys.json
  node6:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "6"]
    volumes:
      - node6:/var/lib/qc3
      - ./keys.json:/keys.json
  node7:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "7"]
    volumes:
      - node7:/var/lib/qc3
      - ./keys.json:/keys.json
  node8:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "8"]
    volumes:
      - node8:/var/lib/qc3
      - ./keys.json:/keys.json
  node9:
    image: qc3:latest
    command: ["/usr/bin/qc3", "test-node", "-i", "9"]
    volumes:
      - node9:/var/lib/qc3
      - ./keys.json:/keys.json

volumes:
  node0:
  node1:
  node2:
  node3:
  node4:
  node5:
  node6:
  node7:
  node8:
  node9:
