on: push
name: Docker Build & Push
jobs:
  privateGoMod:
    name: Private Go Mod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Private Go Mod
      uses: ./.github/actions/make
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: vendor
    - name: Prepare Build Environment
      uses: ./.github/actions/make
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: github-prepare
    - name: Docker Login
      run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build & Push
      run: scripts/ci-dockerbuildpush.sh
      env:
        GITHUB_REF: ${{ github.ref }}
