on: push
name: Docker Build & Push
jobs:
  privateGoMod:
    name: Private Go Mod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Private Go Mod
      uses: ./.github/actions/make
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: vendor
    - name: Prepare Build Environment
      uses: ./.github/actions/make
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: github-prepare
    - name: Docker Login
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Build Container
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t imagebuild .
    - name: Docker Tag Images
      uses: actions/docker/tag@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: imagebuild quorumcontrol/tupelo
    - name: Docker Push Ref Image
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push quorumcontrol/tupelo:${IMAGE_REF}
